@extends('layouts.app')
@section('title','Detalhes do Serviço')
@push('styles')<link rel="stylesheet" href="{{ asset('css/details.css') }}?v={{ filemtime(public_path('css/details.css')) }}">@endpush
@section('content')
@php
 $statusClass=str_replace(' ','-',mb_strtolower($servico->status));
 $podeGerenciarServico=in_array(auth()->user()->permissao,['Administrador','Solicitante'],true);
@endphp
<div class="details-page">
 <nav class="breadcrumb"><a href="{{ route('servicos.index') }}">Solicitações</a><i class="bi bi-chevron-right"></i><span>Detalhes</span></nav>
 <header class="detail-header"><div class="identity"><span class="identity-icon"><i class="bi bi-clipboard2-check"></i></span><div><span class="eyebrow">Solicitação #{{ $servico->id }}</span><h1>{{ $servico->empresa->nome ?? 'Serviço terceirizado' }}</h1><p>Solicitado por {{ $servico->solicitante->name ?? 'usuário não informado' }}</p></div></div><div class="header-actions"><a href="{{ route('servicos.index') }}" class="secondary-btn"><i class="bi bi-arrow-left"></i> Voltar</a>@if($podeGerenciarServico)<a href="{{ route('servicos.edit',$servico) }}" class="primary-btn"><i class="bi bi-pencil"></i> Editar serviço</a>@endif</div></header>
 <section class="summary-grid"><div class="summary-card"><i class="bi bi-calendar-event"></i><span><strong>{{ optional($servico->data_servico)->format('d/m/Y') ?? '—' }}</strong><small>{{ $servico->hora_inicio && $servico->hora_fim ? substr($servico->hora_inicio,0,5).' às '.substr($servico->hora_fim,0,5) : 'Data do serviço' }}</small></span></div><div class="summary-card"><i class="bi bi-activity"></i><span><strong><span class="badge {{ $statusClass }}">{{ $servico->status }}</span></strong><small>Status</small></span></div><div class="summary-card"><i class="bi bi-people"></i><span><strong>{{ $funcionariosElegiveis->count() }}</strong><small>Funcionários regulares da empresa</small></span></div></section>
 <div class="content-grid single"><section class="panel"><div class="panel-header"><div><h2>Regra de acesso</h2><p>A autorização vale para os funcionários regulares da empresa.</p></div></div><div class="description"><strong>Quem poderá entrar?</strong><br>Qualquer funcionário ativo vinculado à {{ $servico->empresa->nome ?? 'empresa' }}, desde que os documentos da empresa e do funcionário estejam dentro da validade configurada. Não existe aprovação manual: a liberação ocorrerá automaticamente na data e no horário do serviço.</div></section><section class="panel"><div class="panel-header"><div><h2>Informações da solicitação</h2><p>Dados do serviço e responsáveis.</p></div></div><dl class="info-grid"><div><dt>Empresa</dt><dd>@if($servico->empresa)@if(auth()->user()->permissao === 'Administrador')<a href="{{ route('empresas.show',$servico->empresa) }}">{{ $servico->empresa->nome }}</a>@else{{ $servico->empresa->nome }}@endif @else—@endif</dd></div><div><dt>Setor</dt><dd>{{ $servico->setor->nome ?? '—' }}</dd></div><div><dt>Solicitante</dt><dd>{{ $servico->solicitante->name ?? '—' }}</dd></div><div><dt>Conclusão</dt><dd>{{ optional($servico->data_conclusao)->format('d/m/Y') ?? 'Ainda não concluído' }}</dd></div></dl><div class="description"><strong>Descrição do serviço</strong><br>{{ $servico->descricao }}</div></section></div>
</div>
@endsection
