@extends('layouts.app')
@section('title','Alertas documentais')
@push('styles')<link rel="stylesheet" href="{{ asset('css/document-alerts.css') }}?v={{ filemtime(public_path('css/document-alerts.css')) }}">@endpush
@section('content')
<div class="alerts-page">
 <header class="alerts-header"><div><span class="eyebrow">Segurança do Trabalho</span><h1>Alertas documentais</h1><p>Acompanhe vencimentos e renove os documentos antes do bloqueio na portaria.</p></div><form method="POST" action="{{ route('alertas-documentos.enviar') }}">@csrf<button><i class="bi bi-envelope-arrow-up"></i> Enviar resumo por e-mail</button></form></header>
 @if(session('success'))<div class="alert-message success">{{ session('success') }}</div>@endif
 @if(session('error'))<div class="alert-message danger">{{ session('error') }}</div>@endif
 @if(!\App\Models\Configuracao::booleano('mail_ativo',false))<div class="alert-message danger">O Outlook ainda não está ativo. Configure o envio em Administração → Configurações.</div>@endif
 <section class="alert-kpis"><article class="danger"><strong>{{ $vencidos }}</strong><span>Vencidos</span></article><article><strong>{{ $vencendo7 }}</strong><span>Vencem em {{ $diasAlertas['critico'] }} dias</span></article><article><strong>{{ $vencendo15 }}</strong><span>Vencem em {{ $diasAlertas['atencao'] }} dias</span></article><article><strong>{{ $vencendo30 }}</strong><span>Vencem em {{ $diasAlertas['preventivo'] }} dias</span></article><article class="neutral"><strong>{{ $semDocumentos }}</strong><span>Sem documentos</span></article></section>
 <section class="mail-info"><i class="bi bi-envelope-check"></i><div><strong>{{ $destinatarios->count() }} destinatário(s) configurado(s)</strong><span>Administradores e Segurança do Trabalho com e-mail cadastrado. Envio automático diário às 07:00.@if($ultimoEnvio) Último envio: {{ \Carbon\Carbon::parse($ultimoEnvio)->format('d/m/Y H:i') }}.@endif</span></div></section>
 <section class="alert-filter"><form method="GET"><label>Buscar<input name="busca" value="{{ request('busca') }}" placeholder="Cadastro, empresa ou arquivo"></label><label>Tipo<select name="tipo"><option value="">Todos</option><option value="Empresa" {{ request('tipo')==='Empresa'?'selected':'' }}>Empresa</option><option value="Funcionário" {{ request('tipo')==='Funcionário'?'selected':'' }}>Funcionário</option></select></label><label>Situação<select name="situacao"><option value="">Todas</option>@foreach(['Vencido',"Vence em até {$diasAlertas['critico']} dias","Vence em até {$diasAlertas['atencao']} dias","Vence em até {$diasAlertas['preventivo']} dias",'Sem documentos'] as $opcao)<option value="{{ $opcao }}" {{ request('situacao')===$opcao?'selected':'' }}>{{ $opcao }}</option>@endforeach</select></label><button><i class="bi bi-search"></i> Filtrar</button><a href="{{ route('alertas-documentos.index') }}">Limpar</a></form></section>
 <section class="alerts-list"><div class="list-title"><h2>Pendências encontradas</h2><span>{{ $itens->count() }} registro(s)</span></div>
 @forelse($itens as $item)<article><span class="document-type"><i class="bi {{ $item['tipo']==='Empresa'?'bi-buildings':'bi-person-vcard' }}"></i></span><div class="document-data"><strong>{{ $item['nome'] }}</strong><small>{{ $item['tipo'] }} · {{ $item['empresa'] }}</small><span>{{ $item['arquivo'] }}</span></div><div class="expiry"><span class="expiry-status {{ Str::slug($item['situacao']) }}">{{ $item['situacao'] }}</span><small>{{ $item['validade'] ? 'Validade: '.$item['validade']->format('d/m/Y') : 'Cadastro incompleto' }}</small></div>@if($item['url'])<a class="renew-link" href="{{ $item['url'] }}"><i class="bi bi-arrow-repeat"></i> Ver e renovar</a>@endif</article>
 @empty<div class="alerts-empty"><i class="bi bi-shield-check"></i><strong>Nenhuma pendência encontrada</strong><span>Os documentos filtrados estão regulares.</span></div>@endforelse
 </section>
</div>
@endsection
