@extends('layouts.app')
@section('title','Detalhes do Funcionário')
@push('styles')
<link rel="stylesheet" href="{{ asset('css/details.css') }}?v={{ filemtime(public_path('css/details.css')) }}">
<link rel="stylesheet" href="{{ asset('css/document-control.css') }}?v={{ filemtime(public_path('css/document-control.css')) }}">
@endpush
@section('content')
@php
 $setor=mb_strtolower(trim((string)auth()->user()->setor));
 $podeGerenciar=auth()->user()->permissao==='Administrador'||in_array($setor,['segurança do trabalho','seguranca do trabalho']);
 $irregulares=$funcionario->documentos->filter(fn($d)=>$d->status_atual==='Vencido');
 $documentacaoRegular=$irregulares->isEmpty();
@endphp
<div class="details-page">
 <nav class="breadcrumb"><a href="{{ route('funcionarios.index') }}">Funcionários</a><i class="bi bi-chevron-right"></i><span>Detalhes</span></nav>
 @if(session('success'))<div class="doc-alert success">{{ session('success') }}</div>@endif @if($errors->any())<div class="doc-alert danger">{{ $errors->first() }}</div>@endif
 <header class="detail-header"><div class="identity"><span class="identity-icon"><i class="bi bi-person-badge"></i></span><div><span class="eyebrow">Funcionário terceirizado</span><h1>{{ $funcionario->nome }}</h1><p>Vinculado à {{ $funcionario->empresa->nome??'empresa não informada' }}</p></div></div><div class="header-actions"><a href="{{ route('funcionarios.index') }}" class="secondary-btn"><i class="bi bi-arrow-left"></i> Voltar</a>@if($podeGerenciar)<a href="{{ route('funcionarios.edit',$funcionario) }}" class="primary-btn"><i class="bi bi-pencil"></i> Editar funcionário</a>@endif</div></header>
 <section class="summary-grid"><div class="summary-card"><i class="bi bi-person-vcard"></i><span><strong>{{ $funcionario->cpf_formatado }}</strong><small>CPF</small></span></div><div class="summary-card"><i class="bi bi-activity"></i><span><strong><span class="badge {{ $funcionario->ativo?'success':'danger' }}">{{ $funcionario->ativo?'Ativo':'Inativo' }}</span></strong><small>Situação cadastral</small></span></div><div class="summary-card"><i class="bi bi-shield-check"></i><span><strong><span class="badge {{ $documentacaoRegular?'success':'danger' }}">{{ $documentacaoRegular?'Regular':'Com pendências' }}</span></strong><small>Situação documental</small></span></div></section>
 <div class="content-grid"><section class="panel"><div class="panel-header"><div><h2>Informações cadastrais</h2><p>Identificação e vínculo empresarial.</p></div></div><dl class="info-grid"><div class="full"><dt>Empresa</dt><dd>@if($funcionario->empresa)<a href="{{ route('empresas.show',$funcionario->empresa) }}">{{ $funcionario->empresa->nome }}</a>@else — @endif</dd></div><div><dt>Cadastrado em</dt><dd>{{ optional($funcionario->created_at)->format('d/m/Y H:i') }}</dd></div><div><dt>Atualizado em</dt><dd>{{ optional($funcionario->updated_at)->format('d/m/Y H:i') }}</dd></div></dl></section>
 <section class="panel"><div class="panel-header"><div><h2>Novo documento</h2><p>Fica válido imediatamente por seis meses.</p></div></div>@if($podeGerenciar)<form class="doc-upload-form" method="POST" enctype="multipart/form-data" action="{{ route('funcionarios.documentos.store',$funcionario) }}">@csrf<label>Arquivo<input type="file" name="arquivo" required accept=".pdf,.jpg,.jpeg,.png"></label><button type="submit" class="primary-btn"><i class="bi bi-cloud-arrow-up"></i> Cadastrar documento</button></form>@else<div class="empty-state"><i class="bi bi-shield-lock"></i><strong>Acesso de consulta</strong><span>O envio é restrito à Segurança do Trabalho.</span></div>@endif</section></div>
 <section class="panel document-history"><div class="panel-header"><div><h2>Histórico documental</h2><p>Todo documento precisa ser renovado a cada seis meses.</p></div></div><div class="document-list">@forelse($funcionario->documentos->sortByDesc('created_at') as $documento)<article class="document-record"><span class="document-icon"><i class="bi bi-file-earmark-text"></i></span><div class="document-main"><div class="document-title"><strong>{{ $documento->nome_original }}</strong><span class="doc-status status-{{ Str::slug($documento->status_atual) }}">{{ str_replace('Proximo','Próximo',$documento->status_atual) }}</span></div><small>Cadastrado em {{ $documento->created_at->format('d/m/Y') }} · válido até {{ optional($documento->validade_ate)->format('d/m/Y')??'não informado' }}</small>@if($documento->observacao_analise)<small class="review-note">{{ $documento->observacao_analise }}</small>@endif</div><div class="document-actions"><a href="{{ route('funcionarios.documentos.download',[$funcionario,$documento]) }}" class="icon-action"><i class="bi bi-download"></i></a>@if($podeGerenciar&&$documento->status==='Pendente')<form class="review-actions" method="POST" action="{{ route('funcionarios.documentos.analisar',[$funcionario,$documento]) }}">@csrf @method('PUT')<input name="observacao_analise" placeholder="Observação (obrigatória ao rejeitar)"><button name="status" value="Aprovado" class="approve"><i class="bi bi-check-lg"></i></button><button name="status" value="Rejeitado" class="reject"><i class="bi bi-x-lg"></i></button></form>@endif @if($podeGerenciar&&in_array($documento->status_atual,['Vencido','Rejeitado']))<button type="button" class="renew-button" onclick="document.getElementById('renew-f-{{ $documento->id }}').hidden=false">Renovar</button>@endif</div>@if($podeGerenciar&&in_array($documento->status_atual,['Vencido','Rejeitado']))<form hidden id="renew-f-{{ $documento->id }}" class="renew-form" method="POST" enctype="multipart/form-data" action="{{ route('funcionarios.documentos.store',$funcionario) }}">@csrf<input type="hidden" name="documento_anterior_id" value="{{ $documento->id }}"><input type="file" name="arquivo" required accept=".pdf,.jpg,.jpeg,.png"><button class="primary-btn">Enviar renovação</button></form>@endif</article>@empty<div class="empty-state"><i class="bi bi-file-earmark"></i><strong>Nenhum documento cadastrado</strong></div>@endforelse</div></section>
</div>
@endsection
