@extends('layouts.app')
@section('title','Detalhes do Funcionário')
@push('styles')<link rel="stylesheet" href="{{ asset('css/details.css') }}?v={{ filemtime(public_path('css/details.css')) }}">@endpush
@section('content')
<div class="details-page">
 <nav class="breadcrumb"><a href="{{ route('funcionarios.index') }}">Funcionários</a><i class="bi bi-chevron-right"></i><span>Detalhes</span></nav>
 <header class="detail-header"><div class="identity"><span class="identity-icon"><i class="bi bi-person-badge"></i></span><div><span class="eyebrow">Funcionário terceirizado</span><h1>{{ $funcionario->nome }}</h1><p>Vinculado à {{ $funcionario->empresa->nome ?? 'empresa não informada' }}</p></div></div><div class="header-actions"><a href="{{ route('funcionarios.index') }}" class="secondary-btn"><i class="bi bi-arrow-left"></i> Voltar</a>@if(auth()->user()->permissao!=='Consulta')<a href="{{ route('funcionarios.edit',$funcionario) }}" class="primary-btn"><i class="bi bi-pencil"></i> Editar funcionário</a>@endif</div></header>
 <section class="summary-grid"><div class="summary-card"><i class="bi bi-person-vcard"></i><span><strong>{{ $funcionario->cpf_formatado }}</strong><small>CPF</small></span></div><div class="summary-card"><i class="bi bi-activity"></i><span><strong><span class="badge {{ $funcionario->ativo?'success':'danger' }}">{{ $funcionario->ativo?'Ativo':'Inativo' }}</span></strong><small>Situação do cadastro</small></span></div><div class="summary-card"><i class="bi bi-files"></i><span><strong>{{ $funcionario->documentos->count() }}</strong><small>Documentos anexados</small></span></div></section>
 <div class="content-grid"><section class="panel"><div class="panel-header"><div><h2>Informações cadastrais</h2><p>Identificação e vínculo empresarial.</p></div></div><dl class="info-grid"><div class="full"><dt>Empresa</dt><dd>@if($funcionario->empresa)<a href="{{ route('empresas.show',$funcionario->empresa) }}">{{ $funcionario->empresa->nome }}</a>@else—@endif</dd></div><div><dt>Cadastrado em</dt><dd>{{ optional($funcionario->created_at)->format('d/m/Y H:i') }}</dd></div><div><dt>Atualizado em</dt><dd>{{ optional($funcionario->updated_at)->format('d/m/Y H:i') }}</dd></div></dl></section>
 <section class="panel"><div class="panel-header"><div><h2>Documentos</h2><p>{{ $funcionario->documentos->count() }} arquivo(s) anexado(s)</p></div>@if(auth()->user()->permissao!=='Consulta')<a href="{{ route('funcionarios.edit',$funcionario) }}" class="panel-action"><i class="bi bi-plus"></i> Adicionar</a>@endif</div><div class="document-list">@forelse($funcionario->documentos as $documento)<div class="document-item"><span class="document-icon"><i class="bi bi-file-earmark"></i></span><span class="document-info"><strong>{{ $documento->nome_original }}</strong><small>Adicionado em {{ $documento->created_at->format('d/m/Y \à\s H:i') }}</small></span><a href="{{ route('funcionarios.documentos.download',[$funcionario,$documento]) }}" class="download-btn"><i class="bi bi-download"></i><span>Baixar</span></a></div>@empty<div class="empty-state"><i class="bi bi-file-earmark"></i><strong>Nenhum documento anexado</strong><span>Os documentos do funcionário aparecerão aqui.</span></div>@endforelse</div></section></div>
</div>
@endsection
